### ISSUE TITLE
select variants according to variant ID or CHROM in R

### ISSUE THREAD

**Issue by afontcub** [knausb/vcfR#102]
Hello, 

I would like to do analyses in R with different subsets of variants of my vcf file. The subset of variants would be defined by a list of "chromosomes".

I know I can do this by creating a separate input vcf file outside R, but in order to make the analyses more flexible, it would be very useful to include the variant selection within the R script.
Isn't there anything in vcfR like   
 dplyr::filter(vcf, CHROM=="scaffold3") 
or
 vcf[vcf$CHROM=="scaffold3",]  ???

Or otherwise is it possible to filter rows of a vcf in R by converting the vcf to another format? 

Many thanks in advance

Amaranta.

**Comment by knausb** [comment]
Hi Amaranta,

Would the following help?

```
library(vcfR)
# Fabricate example data.
data(vcfR_test)
vcf1 <- vcfR_test
vcf2 <- vcfR_test
vcf2@fix[,'CHROM'] <- 'scaffold3'
vcf1 <- rbind2(vcf1, vcf2)
vcf1
# Subset by CHROM
vcf1[getCHROM(vcf1) == '20',]
vcf1[getCHROM(vcf1) == 'scaffold3',]
```

Also see the [vcfR Documentation](https://knausb.github.io/vcfR_documentation/vcfR_object.html) on vcfR objects.

**Comment by afontcub** [comment]
Thank you!!

2018-04-20 19:46 GMT+02:00 Brian Knaus <notifications@github.com>:
