### ISSUE TITLE
adegenet::df2genind check.ploidy

### ISSUE THREAD

**Issue by knausb** [knausb/vcfR#106]
The `adegenet` function `df2genind()` is called by `vcfR::vcfR2genind()` to convert `vcfR` objects to `genind`. The function `df2genind()` has been changed to include the option `check.ploidy` which can improve its performance. This was documented  here https://github.com/thibautjombart/adegenet/issues/231 and here https://github.com/thibautjombart/adegenet/pull/232. While this can be managed by setting an option, I feel that `vcfR2genind()` should include a parameter `check.ploidy` and mention this in its man page. The default should follow `df2genind` by setting its default to `check.ploidy = getOption("adegenet.check.ploidy")`.

**Comment by knausb** [comment]
Yeah, actually that does sound like a better idea. The one thing I do not like about the ellipsis is that it does not make the users options explicit. But your idea will provide more flexibility. And it avoids the situation where I have to wait for `adegenet` to be updated on CRAN before I make the change. And I can add to the documentation to check `??adegenet::df2genind()`. Thanks @zkamvar!

**Comment by knausb** [comment]
On master at 20ef8ec3112e4d95a3317a9b23608e258174fccf. Thanks @zkamvar, thanks @fdchevalier!

**Comment by zkamvar** [comment]
Looks good! A couple of things: users only need to search with one question mark otherwise, the search process takes longer than necessary. Also, you can actually link directly to the df2genind function with \code{\link[=adegenet]{df2genind}{adegenet::df2genind()}}

**Comment by knausb** [comment]
I've had problems with links in the past. I think the issue was when you try to link an uninstalled package. This made me realize that `adegenet` was a Suggests and not an Imports. So I changed this. But I still think that the help system is a little more bullet proof. And it should work if you're not using RStudio. Now on the master branch at: e2e410d30d3252e263d206018d1de22d8195e56d.

**Comment by knausb** [comment]
Back to Suggests at: 9ef130933cef50e3391af130144f25838f254d88.
