### ISSUE TITLE
Utilize viridis for default color ramp

### ISSUE THREAD

**Issue by zkamvar** [knausb/vcfR#11]
The current color ramp for `heatmap.bp` is not colorblind friendly. [Viridis](http://rud.is/b/2015/07/20/using-the-new-viridis-colormap-in-r-thanks-to-simon-garnier/) is a color palette that was explicitly designed for python's matplotlib to tease out large and small differences in data. [Heres a video describing how they came up with the palette](https://www.youtube.com/watch?v=xAoljeRJ3lU). It is available in R as the [package "viridis"](https://cran.r-project.org/web/packages/viridis/index.html).

**Comment by knausb** [comment]
This is now implemented in the branch 'matrix', which is under development.  It will become available in the master branch the next time I merge. Thanks!
