### ISSUE TITLE
write.vcf append includes the @fix header

### ISSUE THREAD

**Issue by Tabima** [knausb/vcfR#12]
Let's assume I have a list of filtered `chrom` objects called `chrom.win`. Each of the elements of a list represent a chromosome, so `chrom.win[[1]]` is chromosome 1.

I'm trying to create an output vcf file using `write.vcf` for each of the elements of the `chrom.win` in order to append all elements into a vcf file that laready has chromosome 1 and all the vcf headers + info:

```
write.vcf(chrom.win[[1]], file="filtered.vcf.gz", mask=T)

for (i in 2:length(chrom.win)){
  write.vcf(chrom.win[[i]],file = filtered.vcf.gz,APPEND = T,mask = T)
}
```
when I open `filtered.vcf.gz` I find the same number of #CHROM headers than chromosomes. I can go around it by creating one vcf file per chromosome and concatenate them using `vcf-tools`, but having the #CHROM header breaks the idea of appending the output, doesn't it?

**Comment by knausb** [comment]
Good point! I've tried to address this in the devel branch. It had a number of side effects. Let me know if it gives you any trouble.

**Comment by Tabima** [comment]
Yes! It works really well. I'll keep on playing with it and get back to you if I find something new.

**Comment by knausb** [comment]
I'll close this. Let me know if it misbehaves.
