### ISSUE TITLE
vcfR reading problem

### ISSUE THREAD

**Issue by OmidJa** [knausb/vcfR#126]
Hello,
Actually I have vcf file of whole genome data which I have generated it from samtools pipeline. Now that I want to check the quality, mapping and depth of the SNPs using vcfR I am facing with an error in reading my vcf file. I will be so grateful if you help me to pass this problem.
Here is the command I used:

`t.vcf=read.vcfR("species.vcf")`

And here is the error:

> Processed variant 136000Error in .read_body_gz(file, stats = stats, nrows = nrows, skip = skip,  :
>   long vectors not supported yet: memory.c:1668

Also when I change my command and verbose=FALSE, still I have the problem.
`t.vcf=read.vcfR("species.vcf", verbose=FALSE)`

> Error in .read_body_gz(file, stats = stats, nrows = nrows, skip = skip,  : long vectors not supported yet: memory.c:1668

Thank you very much in advance,
Omid

**Comment by knausb** [comment]
Hi Omid,

I'm going to guess that you're working with a fairly large file. And the error does not appear to be a vcfR error but is more likely and error thrown by one of the libraries vcfR uses. So I doubt I can fix it. Youi could try reading part of the file in.

```
vcf <- read.vcrfR("species.vcf", nrows = 1000)
```

It is possible you have a mal-formed file. If the above works you can increase `nrows` so you can isolate the line that causes problems.

When I have files that are too large to read into memory my current solution is to divide the project into chromosomes (or contigs as is usually the case). I have some documentation below.

https://knausb.github.io/vcfR_documentation/subset_data_to_1chrom.html

Please let me know if this addresses your issue. Good luck!
Brian

**Comment by OmidJa** [comment]
Dear Brian,
Thank you very much for your great help. By subsetting the vcf file based on chromosomes now it is working properly. Also I should add this point that when I changed my using server/cluster, without subsetting the vcf file got read by vcfR package well.

I am really grateful for your support.
Regards,
Omid

**Comment by knausb** [comment]
Glad I could help. Good luck with your research!
