### ISSUE TITLE
numeric sample names in read.vcfR

### ISSUE THREAD

**Issue by jessepoland** [knausb/vcfR#129]
Numeric sample names are appended with 'X'. 

Example 001ET_D becomes "X001ET_D" 

This issue is related to #2 for read.vcf
https://github.com/knausb/vcfR/issues/2

**Comment by knausb** [comment]
Hi @jessepoland, that sounds like an R thing. But I'm not reproducing it.

``` r


library(vcfR)
#> 
#>    *****       ***   vcfR   ***       *****
#>    This is vcfR 1.8.0 
#>      browseVignettes('vcfR') # Documentation
#>      citation('vcfR') # Citation
#>    *****       *****      *****       *****
data("vcfR_test")
colnames(vcfR_test@gt)[-1] <- 1:3
colnames(vcfR_test@gt)[2] <- "001ET_D"
vcfR_test@gt
#>      FORMAT        001ET_D          2                3             
#> [1,] "GT:GQ:DP:HQ" "0|0:48:1:51,51" "1|0:48:8:51,51" "1/1:43:5:.,."
#> [2,] "GT:GQ:DP:HQ" "0|0:49:3:58,50" "0|1:3:5:65,3"   "0/0:41:3"    
#> [3,] "GT:GQ:DP:HQ" "1|2:21:6:23,27" "2|1:2:0:18,2"   "2/2:35:4"    
#> [4,] "GT:GQ:DP:HQ" "0|0:54:7:56,60" "0|0:48:4:51,51" "0/0:61:2"    
#> [5,] "GT:GQ:DP"    "0/1:35:4"       "0/2:17:2"       "1/1:40:3"

orig_dir <- getwd()
setwd(tempdir())

write.vcf(vcfR_test, file = "vcfR_test.vcf.gz")

my_vcf <- read.vcfR("vcfR_test.vcf.gz", verbose = FALSE)
my_vcf@gt
#>      FORMAT        001ET_D          2                3             
#> [1,] "GT:GQ:DP:HQ" "0|0:48:1:51,51" "1|0:48:8:51,51" "1/1:43:5:.,."
#> [2,] "GT:GQ:DP:HQ" "0|0:49:3:58,50" "0|1:3:5:65,3"   "0/0:41:3"    
#> [3,] "GT:GQ:DP:HQ" "1|2:21:6:23,27" "2|1:2:0:18,2"   "2/2:35:4"    
#> [4,] "GT:GQ:DP:HQ" "0|0:54:7:56,60" "0|0:48:4:51,51" "0/0:61:2"    
#> [5,] "GT:GQ:DP"    "0/1:35:4"       "0/2:17:2"       "1/1:40:3"

setwd(orig_dir)
```

<sup>Created on 2019-03-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Is it possible you're using an old version of `vcfR`? Thanks!

**Comment by jessepoland** [comment]
@knausb , thanks.  You are right.  I looked at it a little closer and the import and creation of the vcfR object is working ok.  The problem is coming with the extraction of the genotypes.  

`> vcf= read.vcfR(file="/Users/jpoland/Documents/ethiopia-pvs/panel_data/diversity.panel.svevo.positions.q10_FILTER.vcf")  
Scanning file to determine attributes.
File attributes:
  meta lines: 10
  header_line: 11
  variant count: 34405
  column count: 430
Meta line 10 read in.
All meta lines processed.
gt matrix initialized.
Character matrix gt created.
  Character matrix gt rows: 34405
  Character matrix gt cols: 430
  skip: 0
  nrows: 34405
  row_num: 0
Processed variant: 34405
All variants processed
> vcf@gt[1:5,1:5]
     FORMAT 001ET_D 002ET_D 003ET_D 004ET_D
[1,] "GT"   "0/0"   NA      "0/0"   "0/0"  
[2,] "GT"   "0/0"   "0/0"   "0/0"   "0/0"  
[3,] "GT"   "0/0"   "0/0"   "0/0"   "0/0"  
[4,] "GT"   "1/1"   "1/1"   "1/1"   "1/1"  
[5,] "GT"   "0/0"   "0/0"   "0/0"   "0/0"  
> 
> geno = data.frame(extract.gt(vcf))
> geno[1:5,1:5]
              X001ET_D X002ET_D X003ET_D X004ET_D X005ET_D
BS00000066_51      0/0     <NA>      0/0      0/0      0/0
BS00000905_51      0/0      0/0      0/0      0/0      0/0
BS00001059_51      0/0      0/0      0/0      0/0      0/0
BS00001364_51      1/1      1/1      1/1      1/1      1/1
BS00001450_51      0/0      0/0      0/0      0/0      0/0`

**Comment by knausb** [comment]
No worries! Thanks for the feedback.
