### ISSUE TITLE
vcfR2genlight

### ISSUE THREAD

**Issue by zkamvar** [knausb/vcfR#13]
You currently have the ability to transfer from vcfR to loci, genind, and DNAbin. As it is clear that genind objects are memory hogs (creating a separate column for each allele), it might be beneficial to also include a vcfR2genlight function, which would be able to store binary SNP data. 

Benefits: 

 - This gives the user a versatile way to transfer their data into genlight format so they can calculate the index of association and DAPC quickly. 
 - The function can automatically insert the allele calls and position information (which the user must do manually for genlight)

Drawbacks: 

 - All alleles going in should be binary.

I know it's not a priority by any means, but it's something to think about as a way to get around the memory issue and make things more accessible.

**Comment by knausb** [comment]
I've created vcfR2genlight. Default behavior when encountering loci with more that two alleles is to throw a warning and omit these loci. Its also been added to the vignette on converting data. These additions are currently only in the devel branch.
