### ISSUE TITLE
Error in .shlib_internal(args) :    C++11 standard requested but CXX11 is not defined

### ISSUE THREAD

**Issue by tedtoal** [knausb/vcfR#139]
On June 25 2019 I'm trying to do install.packages("vcfR") on an UBUNTU machine running R v3.6.0, and I get this error:

`Error in .shlib_internal(args) :    C++11 standard requested but CXX11 is not defined`

Searching for help on this error doesn't reveal why this doesn't work, mainly it just suggests adding some CXX11 definitions to a local user-based R config file.

**Comment by knausb** [comment]
Hi @tedtoal , I run Ubuntu 16.0.4 and R 3.6.0 and vcfR 1.8.0 builds just fine. I asked a colleague with the same set up and he built it fine. I tried [Rhub](https://builder.r-hub.io/status/vcfR_1.8.0.tar.gz-c83034a7a0ba343028cfb380f2cc05a4) which did error. But that was because it couldn't find adegenet, which looks fine on CRAN. So I can't reproduce your reported behaviour. Is it possible that this is system specific? Can you try to build it on a colleagues computer? Thanks!
Brian

**Comment by knausb** [comment]
You could also try the master branch here on GitHub. We're overdue for an update and this would get you there before it shows up on CRAN.

**Comment by tedtoal** [comment]
Hi @knausb, It also fails when I try it on a different server computer which has its own OS, but both computers share drives, and the R I am trying to install into is on the shared drives.

The R I’m trying to install into was built by me in order to enable the build option —enable-R-shlib.  It is built within a Conda environment and uses the following ./configure line:

./configure --prefix=$CD --with-cairo --enable-R-shlib CPPFLAGS='-I$I1 -L$L1 -L$L2' LDFLAGS='-L$L1 -L$L2 -Xlinker -rpath-link=$L1:$L2'"
        ./configure --prefix=$CD --with-cairo --enable-R-shlib CPPFLAGS="-I$I1 -L$L1 -L$L2" LDFLAGS="-L$L1 -L$L2 -Xlinker -rpath-link=$L1:$L2”


where $CD = local install prefix
 I1=$CD/include
 L1=$CD/lib
 L2=$L1/R/lib
     
I wonder if my CPPFLAGS= argument might be somehow breaking it?

**Comment by knausb** [comment]
Hi @tedtoal , I am at home now where I have another machine running Ubuntu 16.04 and R 3.6.0 and vcfR 1.8.0 built successfully. So I've now built it on three Ubuntu machines running R 3.6.0. And for completeness, Travis builds but they're not at R 3.6.0, so I do not think that is relevant.

I'm used to setting compiler options in Makevars files. For example, vcfR has a src/Makevars file that includes the following.

```
## We need some libraries
PKG_LIBS = -lz

## Compiler flags
CXX_STD = CXX11
```
This may be where your error is generated. The system has Makevars too, but I'm not too familiar with them. You might find some information on this in [Writing R extensions](https://cran.r-project.org/manuals.html#R-exts). My interpretation of your error is that somewhere the environment variable CXX11 has become unset (e.g., clobbered) or perhaps not set in the first place. The Ubuntu machines I have access to all appear to have it. Could it have something to do with the Conda environment? That's something I do not use, so I'm probably not going to be a lot of help there.

Please let me know if you come up with a solution or if I can provide more information!
Brian

**Comment by tedtoal** [comment]
Hi @knausb, my ubuntu machines do not have a CXX11 environment variable.  Are you sure you mean environment variable?  I did this:

echo $CXX11

and got nothing, whether or not conda was loaded.
Ted

**Comment by knausb** [comment]
Hi @tedtoal , you are correct, I miss spoke. This is not an "environment" variable, but appears to be a variable passed to make. I found some good info [here](https://stackoverflow.com/a/43599233). In my /etc/R/Makeconf I find the following line.

```
CXX11 = g++
```

This is a read everyone file, so you should be able to see it. But you'll probably need a sysadmin to change it.

If you can't edit this file you might try adding the above line to your `~/.R/Makevars`. Or adding it to the `vcfR/src/Makevars` file.

**Comment by tedtoal** [comment]
I can probably fix it that way, but I'd rather find out why the problem exists in the first place, so it doesn't show up the next time somebody upgrades R on our system.

I see that when I ran ./configure for R, it tested for the various C++ compiler standards, and those tests failed, and the reason they failed is that the test command line had a -std=<std to test> option followed subsequently in the same command line by -std=c++17.  And apparently the reason that happens is that Conda defines CXXFLAGS=... -std=c++17 ..., and the configure script expands CXXFLAGS in that command line.  I don't think the problem is with Conda, but with the R configure script.  I think I'll report it as an R bug.  This is R version 3.5.3.  It may be fixed in version 3.6 of R, but I'm not ready to install that yet.

**Comment by knausb** [comment]
I've never built R from source. I use `apt-get`, which I suppose builds it from source. But it keeps me ignorant about these details so I wouldn't know where to find a config file, or if it was cleaned up for me. Good luck!

**Comment by tedtoal** [comment]
I ultimately fixed the problem by redefining CXXFLAGS to omit the -std=c++17, just before I do R ./configure:

'''
SAVE_CXXFLAGS="$CXXFLAGS"
CXXFLAGS="${CXXFLAGS/-std=c++17/}"
./configure --prefix=$CD --with-cairo --enable-R-shlib CPPFLAGS="-I$I1 -L$L1 -L$L2" LDFLAGS="-L$L1 -L$L2 -Xlinker -rpath-link=$L1:$L2"
CXXFLAGS="$SAVE_CXXFLAGS"
'''

./configure was then able to properly detect the compiler support for the different C versions.
