### ISSUE TITLE
Add relevant information to vcfR2genlight

### ISSUE THREAD

**Issue by zkamvar** [knausb/vcfR#14]
Hi Brian,

Thank you again for making vcfR2genlight a reality. I have one more request:

Since the VCF file possibly contains the chromosomal locations of each SNP along with their genotype and other information, it would be useful to include that information as well. I would make a pull request, but I'm not quite sure the proper way to access that information from a vcfR or chrom object at the moment.

You can set these values like so:

```r
chromosome(x) <- chromosome_vector # vector with the chromosome designation for each SNP
position(x)   <- position_vector # vector containing the numeric position of each SNP along the chromosome
alleles(x)    <- genotype_vector # vector of genotypes coded as A/C...
indNames(x)   <- sample_names # vector of sample designators
locNames(x)   <- locus_names # vector of locus names
```

**Comment by knausb** [comment]
Hi Zhian,

You may not be familiar with the vcfR object, but I'm not very familiar with the genlight object. So I appreciate the example you posted. The devel branch has been updated to add this information to the genlight object. I'd appreciate if you could validate that this is what you were expecting. There is an example of using this function in the vignette 'converting_data'. Be forewarned that the example did not include interesting info for locNames, but I do think its implemented correctly.

Thank you!

**Comment by zkamvar** [comment]
I will check this and close it once validated. 

Thank you for the work, Brian!

**Comment by zkamvar** [comment]
Hi Brian,

I tried following the vignette "converting_data.Rmd", but I ran into trouble because the pinfsc50 package didn't exist on my machine. I installed it, followed the steps and it worked. There are no locus names, however because the ID column of the fix slot contains all NAs

**Comment by knausb** [comment]
Hi Zhian,

Variant callers, such as SAMTools, FreeBayes or the GATK's haplotype caller, typically do not populate ID slot of vcf format files. This field is typically encoded as '.' in the vcf file and is converted to 'NA' in the vcfR object. This is a field from a valid vcf file and I feel I've handled it in an R appropriate manner.  See this link for the vcf definition.

http://samtools.github.io/hts-specs/

The ID field will be populated from other sources (e.g., someone included it in dbSNP). When these annotations are included in the ID field they should be included in the vcfR@fix[,'ID'] field which should be inserted into locNames(x) by vcfR2genlight. The present example simply doesn't illustrate this well.

Thanks for closing this!
Brian
