### ISSUE TITLE
Support for bcf files

### ISSUE THREAD

**Issue by explodecomputer** [knausb/vcfR#143]
Thanks for a very useful package. Do you have plans to allow vcfR to read bcf files? If not do you know of any that will?

**Comment by knausb** [comment]
I do not know of any R packages that will read BCF files. At some point I think I benchmarked BCF and the gzipped VCF and decided they performed very similarly. I would like to incorporate htslib into vcfR. #124 and #125 request this. However, I have yet to learn how to actually do this, and have not found a lot of time to code lately. So these have not been a high priority.

**Comment by explodecomputer** [comment]
Thanks for the fast reply!
I did a bit of research and it seems that [VariantAnnotation](https://bioconductor.org/packages/release/bioc/html/VariantAnnotation.html) will, though some of its functionality seems to break (e.g. reading just regions).
