### ISSUE TITLE
Missing license version 

### ISSUE THREAD

**Issue by jenzopr** [knausb/vcfR#144]
Dear maintainer,

We noticed that you list `GPL` as `License` in your `Description` file. Can you clarify the specific GPL version your package is licensed under (e.g. `GPL-2` or `GPL-3`)?

On behalf of bioconda and conda-forge teams,
Jens

#### Technical background
Your package is currently available on the [bioconda](https://bioconda.github.io/) conda channel. We'd like to migrated the package to [conda-forge](https://conda-forge.org/). conda-forge requires inclusion of the license text during packaging. The R distribution already contains some licenses, but `GPL` is not one of them (however, `GPL-2` and `GPL-3` are included). Let me know if you need further information.

**Comment by knausb** [comment]
Thanks for bringing this to my attention! I've changed `GPL` to `GPL-3` on the master branch. I'm feeling like we're overdue for a post to CRAN. I've got some open issues I was hoping to get to but I may have to learn to accept those. So hopefully this change will arrive on CRAN sooner than later.

**Comment by jenzopr** [comment]
Nice! Thanks a lot for the fast reply 👍
