### ISSUE TITLE
vcfR2tidy error (Can't combine `..1$tt` <logical> and `..2$tt` <character>.)

### ISSUE THREAD

**Issue by fpsom** [knausb/vcfR#159]
First of all, thanks @knausb for creating and maintaining this very useful package!

I was testing my existing scripts (after the recent update of R4.0.0 and dplyr), and I came across the following error:

```
library(vcfR)
data("vcfR_test")
vcfR_test
```

Output normal
```
***** Object of Class vcfR *****
3 samples
1 CHROMs
5 variants
Object size: 0 Mb
0 percent missing data
*****        *****         *****
```

Attempting to run `vcfR2tidy`
```
vcfR2tidy(vcfR_test)
```

Error
```
Error: Can't combine `..1$tt` <logical> and `..2$tt` <character>.
Run `rlang::last_error()` to see where the error occurred.
```

I assume that this is due to the recent update, but I cannot pinpoint where the particular error might be. 

If there are any suggestions on how to move around actually calling `vcfR2tidy`,  they would be very helpful (given also the fact that you probably have extremely limited time).

**Comment by knausb** [comment]
Hi @fpsom ,

Thank you for bringing this to my attention! And thank you for providing a mre. It sounds like you are aware of this, but there have been some major changes in the R universe lately. In April R 4.0.0 was released and in May dplyr 1.0.0 was released. I appear to have addressed this issue in my development version. If you'd like to try it you can use the following.

```
devtools::install_github(repo="knausb/vcfR")
```

I've been struggling with dependency issues associated with R 4.0.0. But I think I'm finally at a place where I can update the CRAN version. Hopefully this week.

Thanks!
Brian

**Comment by fpsom** [comment]
Hi @knausb ! Thank you very much for the swift reply!

I've just checked with the `dev` version, and it works absolutely fine - including some additional `vcfR` function calls I had in the test.

Thanks again!

**Comment by skanwal** [comment]
Hi @knausb,

First, thanks for the great resource.
I am hitting the same issue as originally posted by Fotis.

I am also not able to install the development version.

```
Downloading GitHub repo knausb/vcfR@master
✓  checking for file ‘/private/var/folders/_v/g24brqws13v3gtrvcz2j57ldbdw8jg/T/RtmpvIKCnE/remotese18e215e69a0/knausb-vcfR-5fb215b/DESCRIPTION’ ...
─  preparing ‘vcfR’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  running ‘cleanup’
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘vcfR_1.11.0.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'
   
* installing *source* package ‘vcfR’ ...
** using staged installation
./configure: line 4: checkbashisms: command not found
Error in system(cmd) : (converted from warning) error in running command
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/vcfR’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/vcfR’
Error: Failed to install 'vcfR' from GitHub:
  (converted from warning) installation of package ‘/var/folders/_v/g24brqws13v3gtrvcz2j57ldbdw8jg/T//RtmpvIKCnE/filee18e1df3560a/vcfR_1.11.0.tar.gz’ had non-zero exit status
```
I am trying to install it on MAC and my R version is 4.0.0.

Did you mange to update the CRAN version? The vcfR version I currently have is:

```
   *****       ***   vcfR   ***       *****
   This is vcfR 1.10.0 
     browseVignettes('vcfR') # Documentation
     citation('vcfR') # Citation
   *****       *****      *****       *****
```
