### ISSUE TITLE
installation of master fails for missing checkbashisms 

### ISSUE THREAD

**Issue by jan-glx** [knausb/vcfR#160]
```
devtools::install_github(repo="knausb/vcfR")
Downloading GitHub repo knausb/vcfR@master
✓  checking for file ‘/tmp/RtmpqOTXiK/remotes1c102254e545/knausb-vcfR-6c2b1d3/DESCRIPTION’ (926ms)
─  preparing ‘vcfR’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  running ‘cleanup’
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘vcfR_1.11.0.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   
Installing package into ‘/rsession-store/gleixner/R/4.0.0’
(as ‘lib’ is unspecified)
* installing *source* package ‘vcfR’ ...
** using staged installation
./configure: line 4: checkbashisms: command not found
Error in system(cmd) : (converted from warning) error in running command
* removing ‘/rsession-store/gleixner/R/4.0.0/vcfR’
 Error: Failed to install 'vcfR' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpqOTXiK/file1c102c445fc0/vcfR_1.11.0.tar.gz’ had non-zero exit status 
```
This is on `R 4.0.0` on  `CentOS Linux 7`.  The dev  branch (still) works.
Should this configure script be here at all, or was it perhaps committed by accident?

**Comment by kopeckyl** [comment]
Same error here

**Comment by knausb** [comment]
Hi @jan-glx and @kopeckyl ,

I believe I am aware of this and am working on a solution. Thank you for letting me know though! During building and testing in R 4.0.0 a warning was generated stating that a complete check required `checkbashisms`. This was new to me, but I installed it and the warning went away. Subsequent to publication of vcfR 1.11.0 I received a message from CRAN stating that `checkbashisms` was not standard on many systems and is more of a Debian thing. So I think I need to work on a script that first tests for whether `checkbashisms` is installed. In the mean time you can comment out the line with `checkbashisms` in the file "configure" or omit the "configure" file all together. It should build after that. Please let me know if this helps!
Brian

**Comment by kopeckyl** [comment]
@knausb and @jan-glx 

I managed to install it by running this command in your terminal (I am using linux ubuntu):

`sudo apt install devscripts`

This should install checkbashisms in your machine and the installation will work.

If you are using mac this should also work:

`brew install checkbashisms`

**Comment by jan-glx** [comment]
I guess you got this warning:
```
* checking top-level files ... WARNING
A complete check needs the 'checkbashisms' script
```
@knausb I believe this means that `R CMD check  --as-cran` requires `checkbashisms` to be avaiable on the system that runs `R CMD check` to check that `configure` scripts are portable, but CRAN by no means requires the package itself to use `checkbashism` (after all this would make the package *less* portable).

See also [R Internals](https://cran.r-project.org/doc/manuals/r-devel/R-ints.html):

> _R_CHECK_BASHISMS_
> 
>     Check the top-level scripts configure (unless generated by autoconf) and cleanup for non-Bourne-shell code, using the Perl script checkbashisms if available. This includes reporting scripts using the non-portable #! /bin/bash. (Script checkbashisms is available in most Linux distributions in a package named either ‘devscripts’ or ‘devscripts-checkbashisms’ and from https://sourceforge.net/projects/checkbaskisms/files.) Default: false (but true for CRAN submission checks except on Windows).

**Comment by zorgster** [comment]
> @knausb and @jan-glx
> 
> I managed to install it by running this command in your terminal (I am using linux ubuntu):
> `sudo apt install devscripts`

I'll extend this answer - I do not have superuser privileges so I cannot run `apt-get install devscripts`:

`apt-get download devscripts`
`dpkg -x devscripts_2.16.2ubuntu3_amd64.deb ~/software/devscripts/`
`cp ~/software/devscripts/checkbashisms/usr/bin/checkbashisms ~/bin`

[Assuming ~/bin is in your path and check the filename for devscripts...]

Now R gets past the error requiring checkbashisms and vcfR has loaded.

**Comment by knausb** [comment]
You can also just download

```
https://sourceforge.net/projects/checkbaskisms/
```

and place it in your path. No need for admin privileges.

**Comment by knausb** [comment]
Trying to connect redundant issues here, please see #165.
