### ISSUE TITLE
Impending CRAN retirement?

### ISSUE THREAD

**Issue by katiesaund** [knausb/vcfR#163]
It looks like vcfR is going to get retired from CRAN soon. If, in fact, vcfR is going to be retired/abandoned would you consider changing the license to something more permissible (e.g. MIT license) so some functions can be copied/pasted into other packages?

**Comment by padpadpadpad** [comment]
Why do you think this? Would be such a shame to leave it, especially after all the extra development that has been done this year.

**Comment by knausb** [comment]
Hi @katiesaund and @padpadpadpad , I think this has been resolved as miscommunication. When CRAN finds a problematic package on their repo they tend to send a message that says something like "fix this by this date or you'll be removed from CRAN." My interpretation is that this is simply brief, the CRAN folks are all volunteers. But it can be a bit stressful to see this. For clarification, I am presently working on an update to vcfR that I hope will address the concerns of CRAN. And if that one doesn't work, I'll just have to try again. Thanks!

**Comment by jonathan-velotta** [comment]
vcfR is currently off CRAN! I tried to install it just today
