### ISSUE TITLE
not available for R4.0

### ISSUE THREAD

**Issue by sariya** [knausb/vcfR#169]
`
install.packages("vcfR")
`
I get error as:

```
Warning message:
package ‘vcfR’ is not available (for R version 4.0.0)

```
R4.0 debian platform.

**Comment by knausb** [comment]
This issue has already been reported in other issues. Please do not post redundant issues.

**Comment by sariya** [comment]
Sorry, didn't find any issue open for R4.0. 

I used `devtools::install_github(repo="knausb/vcfR")` and installed successfully `vcfR_1.12.0.tar.gz`
I was able to install it with no issues. :)

Found the hack on closed https://github.com/knausb/vcfR/issues/168

vcfR 1.11.0 Released on CRAN 2020-06-05 
CRAN removed this library `Archived on 2020-07-05`  https://cran.r-project.org/web/packages/vcfR/index.html

If there's any appropriate open issue please leave link here for future users.

Cheers,

**Comment by igordot** [comment]
> Sorry, didn't find any issue open for R4.0.

This is not specific to any version of R. It's currently not available on CRAN in general. This issue has a lot of background info and updates: https://github.com/knausb/vcfR/issues/165

**Comment by knausb** [comment]
Thank you @igordot ! I've been struggling with posts like this and appreciate your help!
Brian
