### ISSUE TITLE
Subset or downsample a VCF file?

### ISSUE THREAD

**Issue by vertesy** [knausb/vcfR#179]
Hello, 

thanks for the great package!

Is there function to subset  or downsample a VCF file that is already read in?
I am aware of `read.vcfR( ..., nrows=100)`. 

Thanks,
Abel

**Comment by knausb** [comment]
Hi Abel,

I think we've already addressed this in the documentation.

https://knausb.github.io/vcfR_documentation/vcfR_object.html#subsetting

http://grunwaldlab.github.io/Population_Genetics_in_R/gbs_analysis.html#subsetting-a-vcfr-object-to-200-random-variants

Please let me know if this helps you or not.

Thanks!
Brian

**Comment by vertesy** [comment]
Great, thank you! 
(+ sorry for overlooking it)
