### ISSUE TITLE
How can I add population information to genind converted using vcfR2genind?

### ISSUE THREAD

**Issue by kopelol** [knausb/vcfR#194]
Hi everyone,

How can I add population information to genind converted using vcfR2genind?

I have vcf file(obtained using Snippy) and population information.
I can use vcfRgenind successfully, and I'd like to add population data for further analysis.
I found some ways.
For example, is this the right way?

genind <- vcfR2genind("core.vcf") #for example n=5
pop.data <- c(aaa,bbb,ccc,ddd,eee) #aaa ... are population name.
genind@pop <- as.factor(pop.data)

And how can I check correspondence between Individual name and population name?
Do I have to input population data in order of Individual name included vcf file?

Thanks,

**Comment by knausb** [comment]
Hi @kopelol , did you look at the sections on [GBS analysis](https://grunwaldlab.github.io/Population_Genetics_in_R/gbs_analysis.html) and [genome analysis](https://grunwaldlab.github.io/Population_Genetics_in_R/analysis_of_genome.html)? I think you might find what you're looking for there.

Thanks!
Brian

**Comment by kopelol** [comment]
Hi @knausb 
Thank you for your advice!
I'll check the link.
Thank you.
