### ISSUE TITLE
gene/chromosome annotation

### ISSUE THREAD

**Issue by umasstr** [knausb/vcfR#202]
Hi Brian, thank you for releasing a really well-made package. 

I am having trouble understanding what the GFF is used for. From the tutorial, it doesn't look like there's a way to annotate gene names/position on heatmaps, qc plots etc. Ideally, I would like to annotate genes at which there is an SNV found. 

Somewhat related, I was hoping to make end-to-end chromosome plots. I'm dealing with several samples (25) and It would be great not to have to plot the chromosomes one-by-one. 

Any advice you could provide would be much appreciated!

**Comment by knausb** [comment]
Hi @umasstr ,

The GFF is used to plot annotations in the chrom plot. I don't think it'll help you making annotation though.

In order to make end-to-end chromosomes you could try the following.

```
?vcfR::rePOS()
```

Good luck!
Brian

**Comment by umasstr** [comment]
Thanks!
