### ISSUE TITLE
heatmap.bp fails unless viridisLite is in imports

### ISSUE THREAD

**Issue by zkamvar** [knausb/vcfR#21]
if the user does not have *viridisLite* installed, the `heatmap.bp()` function will fail because it has no color palette:

```r
library("vcfR")
x <- as.matrix(mtcars)
heatmap.bp(x)
#> Error in loadNamespace(name) : there is no package called ‘viridisLite’
```

This can be remedied by placing *viridisLite* in the `Imports` section of your `DESCRIPTION`, ensuring that the user has access to this package.

**Comment by knausb** [comment]
Fixed in bf8e7eead740084448f523976a1ed4d73c0984fe
