### ISSUE TITLE
Bug in parsing header due to `=` sign in the Description

### ISSUE THREAD

**Issue by bounlu** [knausb/vcfR#216]
If there is `=` sign in the description field in the header section, the parsing with `vcfR2tidy` is truncated.

For ex, if the VCF header includes below line:

`##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth (reads with MQ=255 or with bad mates are filtered)">`

`vcfR` meta is parsed by `vcfR2tidy()` like this:

```
Tag	ID	Number	Type	Description
FORMAT	gt_DP	1	Integer	255 or with bad mates are filtered)
```

**Comment by knausb** [comment]
Hi @bounlu , let's start by creating a minimal reproducible example based on your post.

``` r
  library(vcfR)
#> 
#>    *****       ***   vcfR   ***       *****
#>    This is vcfR 1.15.0 
#>      browseVignettes('vcfR') # Documentation
#>      citation('vcfR') # Citation
#>    *****       *****      *****       *****
  data("vcfR_test")
  vcfR_test@meta[ grep("##FORMAT=<ID=DP", vcfR_test@meta) ] <- '##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth (reads with MQ=255 or with bad mates are filtered)">'  
  my_fnames <- vcf_field_names(vcfR_test, tag = "FORMAT")
  my_fnames
#> # A tibble: 4 × 5
#>   Tag    ID    Number Type    Description                        
#>   <chr>  <chr> <chr>  <chr>   <chr>                              
#> 1 FORMAT GT    1      String  Genotype                           
#> 2 FORMAT GQ    1      Integer Genotype Quality                   
#> 3 FORMAT DP    1      Integer 255 or with bad mates are filtered)
#> 4 FORMAT HQ    2      Integer Haplotype Quality
```

<sup>Created on 2024-12-26 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

I see that row 3 of `my_fnames` reproduces the behavior you reported in the 'Description' column.

**Comment by knausb** [comment]
The function `vcfR::vcf2tidy()` calls `vcf_field_names()` which then calls the internal function `getValue()` which uses the regular expression `myValue <- sub(".*=", "", myValue)` to remove the 'key' from the key-value pairs. This is being unsuccessful when the value includes an equals sign (`=`). Changing this regex to `myValue <- sub("^[^=]+=", "", myValue)` appears to resolve this. The regex is explained as follows. The carrot (`^`) anchors the query to the beginning of the string. The character class `[^=]` matches any character except the equals sign. The plus sign (`+`) matches the preceding character one or more times. Finally, the equals sign (`=`) delimits our key-values and our match here substitutes it.

This change has been made and is currently in the devel branch. If you would like to test this you can as follows (requires compilation).

```
devtools::install_github(repo="knausb/vcfR@devel")
library(vcfR)
```

Please let me know if that resolves this issue. 
Thanks! 
Brian

**Comment by bounlu** [comment]
Yes, installing the devel version resolved the issue. Thanks for the quick fix, I appreciate a lot.
