### ISSUE TITLE
vcfR2Dnabin converts one row matrix to character vector

### ISSUE THREAD

**Issue by shankarkshakya** [knausb/vcfR#47]
vcf file with only one variant threw an error  (shown below). The error was it was converting one row matrix to character vector.  

Error in variants[pos >= start.pos, , ] : 
  incorrect number of dimensions

    variants <- variants[pos < start.pos + dim(ref.seq)[2], ]

Solution:

    variants <- variants[pos < start.pos + dim(ref.seq)[2], drop = FALSE]

**Comment by knausb** [comment]
Good catch Shankar! I've made the update and created a test to make sure it stays fixed. I've just pushed it to the devel branch and hopefully we can get this updated on CRAN soon.

Thanks!
