### ISSUE TITLE
Wrap tests in `test_that` function; add content to testthat.R

### ISSUE THREAD

**Issue by zkamvar** [knausb/vcfR#5]
The tests that are currently in the files to be tested are evaluated by testthat, but they are not true unit tests in that if one fails at the beginning, you have no clue if any others will pass later. Utilizing the function `test_that` with your tests will ensure that all the tests will run, even if one or two fail. 

Example:

currently you have this code in `test_create_chrom.R`:

```r
# create_chrom tests.

# detach(package:vcfR, unload=T)
library(vcfR)
context("create_chrom functions")

data(vcfR_example)

pinf_mt <- create_chrom('pinf_mt', seq=pinf_dna, vcf=pinf_vcf, ann=pinf_gff, verbose=F)
expect_that(pinf_mt, is_a("Chrom"))

pinf_mt <- create_chrom('pinf_mt', seq=pinf_dna, vcf=pinf_vcf, verbose=F)
expect_that(pinf_mt, is_a("Chrom"))

pinf_mt <- create_chrom('pinf_mt', vcf=pinf_vcf, ann=pinf_gff, verbose=F)
expect_that(pinf_mt, is_a("Chrom"))

pinf_mt <- create_chrom('pinf_mt', vcf=pinf_vcf, verbose=F)
expect_that(pinf_mt, is_a("Chrom"))
```
It could easily be converted by adding the `test_that` function using the syntax of:

```r
test_that("something happens", {
  expect_that(code(), equals("something happens"))
})

```

In context, this is how it could be implemented:

```r
# create_chrom tests.

# detach(package:vcfR, unload=T)
library(vcfR)
context("create_chrom functions")

test_that("chrom objects can be created", {
  data(vcfR_example)
  
  pinf_mt <- create_chrom('pinf_mt', seq=pinf_dna, vcf=pinf_vcf, ann=pinf_gff, verbose=F)
  expect_that(pinf_mt, is_a("Chrom"))
  
  pinf_mt <- create_chrom('pinf_mt', seq=pinf_dna, vcf=pinf_vcf, verbose=F)
  expect_that(pinf_mt, is_a("Chrom"))
  
  pinf_mt <- create_chrom('pinf_mt', vcf=pinf_vcf, ann=pinf_gff, verbose=F)
  expect_that(pinf_mt, is_a("Chrom"))
  
  pinf_mt <- create_chrom('pinf_mt', vcf=pinf_vcf, verbose=F)
  expect_that(pinf_mt, is_a("Chrom"))
}
```

Additionally, you should place the following in `testthat.R`:

```r
library("testthat")
test_check("vcfR")
```

**Comment by knausb** [comment]
This issue has been raised at the begininng of my attempt to implement the 'testthat' package.  This will take some time to address.  I'll leave this issue open as I work to address this.

**Comment by zkamvar** [comment]
If you need, I have plenty of examples in poppr: https://github.com/grunwaldlab/poppr/blob/master/tests/testthat/test-genclone.R

**Comment by knausb** [comment]
I've now added a 'test_that' statement with an 'expect_' statement to each of the files in testthat.  At present they are basic, but this will grow through time.
