### ISSUE TITLE
Feature request: include sample-specific subsetting in vcfR objects

### ISSUE THREAD

**Issue by zkamvar** [knausb/vcfR#59]
I noticed that subsetting a vcfR object is not as straightforward as I had hoped. I had wanted to reorder my samples by metadata I had in a separate table, but when I did so, I noticed that I had lost a sample. I then saw that this was a feature since the GT element of the vcfR object always starts with the format column. 

While you do specify that users should approach subsetting with caution in [the online documentation][odoc], it's a bit vague and doesn't reflect what needs to be done to protect the data. Again, the R documentation states this as well, but it's in the methods section that's not easy to search for.

If the user accidentally deletes their FORMAT column, then they are met with an error that tells them about this, but if there's a situation where they subset with a numeric vector that includes 1 at the beginning, they extract the wrong samples (see the example below).

Yes, it's the user's responsibility to ensure their data is treated properly, but this is something that can be taken care of at the package level. 

My suggestions for the request in order from most effective to least effective:

1. If the FORMAT column is uniform for all samples, move it to its own slot. This way, you'll save on memory
2. Keep the FORMAT column and engineer the `[` method to take into account the column when the user subsets their data. 
3. Give a warning or error if the user subsets out their FORMAT column
4. Update your documentation to reflect that the user must offset their numeric subset vectors by one and manually add in the format column (by character, integer, or logical at the beginning of the vector).

[odoc]: https://knausb.github.io/vcfR_documentation/vcfR_object.html#subsetting
``` r
options(width = 100)
library("vcfR")
#> 
#>    *****       ***   vcfR   ***       *****
#>    This is vcfR 1.4.0 
#>      browseVignettes('vcfR') # Documentation
#>      citation('vcfR') # Citation
#>    *****       *****      *****       *****
pkg <- "pinfsc50"
vcf_file <- system.file("extdata", "pinf_sc50.vcf.gz", package = pkg)
vcf <- read.vcfR(vcf_file, verbose = FALSE)
x <- which(1:18%%2 == 1)  # only the odd samples
x
#> [1]  1  3  5  7  9 11 13 15 17
vcf  # Original order
#> ***** Object of Class vcfR *****
#> 18 samples
#> 22,031 variants
#> Object size: 20.9 Mb
#> 7.929 percent missing data
#> *****        *****         *****
head(extract.gt(vcf))
#>                      BL2009P4_us23 DDR7602 IN2009T1_us22 LBUS5 NL07434 P10127 P10650 P11633 P12204
#> Supercontig_1.50_41  "1|1"         "1|1"   "1|1"         "1|1" "1|1"   "1|1"  "1|1"  "1|1"  "1|1" 
#> Supercontig_1.50_136 "0|0"         "0|0"   "0|0"         "0|0" "0|0"   "0|1"  "0|0"  "0|0"  "0|0" 
#> Supercontig_1.50_254 "0|0"         "0|0"   "0|0"         "0|0" "0|1"   "0|0"  "1|1"  "0|0"  "0|0" 
#> Supercontig_1.50_275 "0|0"         "0|0"   "0|0"         "0|0" "0|1"   "0|0"  "1|1"  "0|0"  "0|0" 
#> Supercontig_1.50_386 "0|0"         "0|0"   "0|0"         "0|0" "0|1"   "0|0"  "1|1"  "0|0"  NA    
#> Supercontig_1.50_462 "0|0"         "0|0"   "0|0"         "0|0" "0|1"   "0|0"  "1|1"  "0|0"  "0|0" 
#>                      P13527 P1362 P13626 P17777us22 P6096 P7722 RS2009P1_us8 blue13 t30-4
#> Supercontig_1.50_41  "1|1"  NA    "1|1"  "1|1"      "1|1" NA    "1|1"        "1|1"  "1|1"
#> Supercontig_1.50_136 "0|0"  "0|0" "0|0"  "0|0"      "0|0" NA    "0|1"        "0|0"  "0|0"
#> Supercontig_1.50_254 "0|0"  "0|0" "0|0"  "0|0"      "0|0" NA    "0|0"        "0|0"  "0|0"
#> Supercontig_1.50_275 "0|0"  "0|0" "0|0"  "0|0"      "0|0" NA    "0|0"        "0|0"  "0|0"
#> Supercontig_1.50_386 "0|0"  "0|0" "0|0"  "0|0"      "0|0" NA    "0|0"        "0|0"  "0|0"
#> Supercontig_1.50_462 "0|0"  "0|0" "0|0"  "0|0"      "0|0" NA    "0|0"        "0|0"  "0|0"
vcf[, x]  # Wrong samples
#> ***** Object of Class vcfR *****
#> 8 samples
#> 22,031 variants
#> Object size: 14.3 Mb
#> 5.269 percent missing data
#> *****        *****         *****
head(extract.gt(vcf[, x]))
#>                      DDR7602 LBUS5 P10127 P11633 P13527 P13626 P6096 RS2009P1_us8
#> Supercontig_1.50_41  "1|1"   "1|1" "1|1"  "1|1"  "1|1"  "1|1"  "1|1" "1|1"       
#> Supercontig_1.50_136 "0|0"   "0|0" "0|1"  "0|0"  "0|0"  "0|0"  "0|0" "0|1"       
#> Supercontig_1.50_254 "0|0"   "0|0" "0|0"  "0|0"  "0|0"  "0|0"  "0|0" "0|0"       
#> Supercontig_1.50_275 "0|0"   "0|0" "0|0"  "0|0"  "0|0"  "0|0"  "0|0" "0|0"       
#> Supercontig_1.50_386 "0|0"   "0|0" "0|0"  "0|0"  "0|0"  "0|0"  "0|0" "0|0"       
#> Supercontig_1.50_462 "0|0"   "0|0" "0|0"  "0|0"  "0|0"  "0|0"  "0|0" "0|0"
vcf[, c(0, x) + 1]  # Correct order, but not intuitive
#> ***** Object of Class vcfR *****
#> 9 samples
#> 22,031 variants
#> Object size: 15.9 Mb
#> 8.062 percent missing data
#> *****        *****         *****
head(extract.gt(vcf[, c(0, x) + 1]))
#>                      BL2009P4_us23 IN2009T1_us22 NL07434 P10650 P12204 P1362 P17777us22 P7722
#> Supercontig_1.50_41  "1|1"         "1|1"         "1|1"   "1|1"  "1|1"  NA    "1|1"      NA   
#> Supercontig_1.50_136 "0|0"         "0|0"         "0|0"   "0|0"  "0|0"  "0|0" "0|0"      NA   
#> Supercontig_1.50_254 "0|0"         "0|0"         "0|1"   "1|1"  "0|0"  "0|0" "0|0"      NA   
#> Supercontig_1.50_275 "0|0"         "0|0"         "0|1"   "1|1"  "0|0"  "0|0" "0|0"      NA   
#> Supercontig_1.50_386 "0|0"         "0|0"         "0|1"   "1|1"  NA     "0|0" "0|0"      NA   
#> Supercontig_1.50_462 "0|0"         "0|0"         "0|1"   "1|1"  "0|0"  "0|0" "0|0"      NA   
#>                      blue13
#> Supercontig_1.50_41  "1|1" 
#> Supercontig_1.50_136 "0|0" 
#> Supercontig_1.50_254 "0|0" 
#> Supercontig_1.50_275 "0|0" 
#> Supercontig_1.50_386 "0|0" 
#> Supercontig_1.50_462 "0|0"
```

<details><summary>Session info</summary>

``` r
devtools::session_info()
#> Session info ---------------------------------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.3.2 (2016-10-31)
#>  system   x86_64, darwin13.4.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  tz       America/Chicago             
#>  date     2017-02-17
#> Packages -------------------------------------------------------------------------------------------
#>  package     * version date       source                            
#>  ape           4.1     2017-02-14 CRAN (R 3.3.2)                    
#>  backports     1.0.5   2017-01-18 CRAN (R 3.3.2)                    
#>  cluster       2.0.5   2016-10-08 CRAN (R 3.3.0)                    
#>  devtools      1.12.0  2016-06-24 CRAN (R 3.3.0)                    
#>  digest        0.6.12  2017-01-27 CRAN (R 3.3.2)                    
#>  evaluate      0.10    2016-10-11 cran (@0.10)                      
#>  formatR       1.4     2016-05-09 CRAN (R 3.3.0)                    
#>  htmltools     0.3.5   2016-03-21 CRAN (R 3.2.4)                    
#>  knitr         1.15.6  2016-12-25 Github (yihui/knitr@849f2d0)      
#>  lattice       0.20-34 2016-09-06 CRAN (R 3.3.0)                    
#>  magrittr      1.5     2014-11-22 CRAN (R 3.2.0)                    
#>  MASS          7.3-45  2015-11-10 CRAN (R 3.2.2)                    
#>  Matrix        1.2-8   2017-01-20 CRAN (R 3.3.2)                    
#>  memoise       1.0.0   2016-01-29 CRAN (R 3.2.3)                    
#>  memuse        3.0-1   2016-09-20 cran (@3.0-1)                     
#>  mgcv          1.8-17  2017-02-08 CRAN (R 3.3.2)                    
#>  nlme          3.1-131 2017-02-06 CRAN (R 3.3.2)                    
#>  permute       0.9-4   2016-09-09 cran (@0.9-4)                     
#>  pinfsc50      1.1.0   2016-12-02 CRAN (R 3.3.2)                    
#>  Rcpp          0.12.9  2017-01-14 CRAN (R 3.3.2)                    
#>  rmarkdown     1.3     2016-12-25 Github (rstudio/rmarkdown@3276760)
#>  rprojroot     1.2     2017-01-16 CRAN (R 3.3.2)                    
#>  stringi       1.1.2   2016-10-01 CRAN (R 3.3.0)                    
#>  stringr       1.1.0   2016-08-19 cran (@1.1.0)                     
#>  vcfR        * 1.4.0   2017-01-07 CRAN (R 3.3.2)                    
#>  vegan         2.4-2   2017-01-17 CRAN (R 3.3.2)                    
#>  viridisLite   0.1.3   2016-03-12 CRAN (R 3.2.4)                    
#>  withr         1.0.2   2016-06-20 cran (@1.0.2)                     
#>  yaml          2.1.14  2016-11-12 cran (@2.1.14)
```

</details>

**Comment by knausb** [comment]
Hi Zhian,

Yeah, I have at times been unhappy with how I treated this. And because you've commented on it, it seems like its time to attempt some sort of fix. First off, there is a smaller example data set at

    data(vcfR_test)

Its much smaller that the dataset you used and is nice for examples like this. It is from the VCF specification and illustrates that the FORMAT column does not need to be uniform, different variants may contain different data. So operations on the gt region really need this info. I included it in the gt slot because I felt it was more convenient to pass one matrix back and forth instead of passing a vector and a matrix. But, as you point out, this creates some issues.

I think your answer 2 (modify `[`) would be the most appropriate way to handle this. The problem I see with this is that it will break all code that explicitly includes this column (including my own). Do you have a suggestion on implementing this fix without breaking existing code?

**Comment by knausb** [comment]
Actually, as you point out, the columns can be selected by character, integer or logical. Character and integer can be handled by adding the FORMAT column in `[` and then using `unique()`. Logical remains a problem. Testing the result of `[` with colnames(vcf@gt)[1] == "FORMAT" and thowing a warning if its not there could address this. So a hybrid of 2 and 3. There is no verbose argument to `[` but output could be suppressed with `suppressWarnings()`. It does take `...` and I might be able to pass a verbose parameter with that. I think that would work.

**Comment by knausb** [comment]
That won't handle logicals correctly. We don't know how to tell if `TRUE TRUE` is FORMAT and sample 1 or samples 1 and 2. Still thinking...

**Comment by zkamvar** [comment]
> Character and integer can be handled by adding the FORMAT column in `[` and then using `unique()`. 

In the case of characters, this is the easiest to solve. For integers, this is not as straightforward because it really depends on user intention (if they are trying to subset the samples without knowing the FORMAT column exists, then you need to add 1 to everything). 

> That won't handle logicals correctly. We don't know how to tell if TRUE TRUE is FORMAT and sample 1 or samples 1 and 2. Still thinking...

Logical vectors will almost always come in the same size as the data, so you can check if it's one off and then add the FORMAT column. 

>  It does take ... and I might be able to pass a verbose parameter with that. I think that would work.

This does present another option. You could keep the current behavior and add an argument called "samples" after the `...`. This is the way adegenet allows you to subset specific loci.

**Comment by zkamvar** [comment]
[Here's the example of subsetting by population][adegenet.pop] in adegenet and the [option to reset mlgs][popprsubset] in poppr


[adegenet.pop]: https://github.com/thibautjombart/adegenet/blob/713b8737d2ee64926a35d7ddbf866a30d3b23915/R/basicMethods.R#L29
[popprsubset]: https://github.com/grunwaldlab/poppr/blob/master/R/methods.r#L545-L548

**Comment by knausb** [comment]
Thanks @zkamvar for the examples! I'm still not sure I have a way forward here. But the examples give me some ideas and I'll probably need to take a closer look at them.

My previous suggestion that concatenating 1 onto numerics and using `unique()` will not work because the coordinates will be different. Ideally sample 1 should be column 1 where at present it is column 2.

Problems I need to address.

- Recycled logicals
- Numerics

The adegenet example reminds me to recast factors as characters. I'll have to put some more thought into this.

Adding a warning if FORMAT is removed should be easy and should be added regardless of whether I can get a more elegant answer.

Also keep in mind that the entire gt region is optional. I should make sure to address this with a unit test.

**Comment by knausb** [comment]
And acknowledging that Zhian actually had two replies where the first had good suggestions but for some reason the second ended up at the top of my screen.

**Comment by knausb** [comment]
Added warning when FORMAT is omitted at 68cafdb7b1a4fcd8dcd06725b725cd289519d4bf.

**Comment by knausb** [comment]
I think the best way to handle this would be to create a separate slot for FORMAT. This would break any existing code. I've begun a 'to do' list for v 2.0.0 and put it in NEWS.md and this is the first item.

Thanks and please close if you're satisfied.

**Comment by zkamvar** [comment]
I've been thinking about this one and I think adding a new argument `samples = ` or `inds = ` to the `[` method makes the most sense for the following reasons:

1. It does not break backwards compatibility
2. the argument becomes clear as to what exactly is being subset

**Comment by knausb** [comment]
samples parameter now in: 6c2ae8c0276f57306cff040e025fdc6d00f849d0. Wanna give it a try @zkamvar?

**Comment by zkamvar** [comment]
You missed a setting for integers.

```r
> vcf[samples = x]
Error in .local(x, i, j, ..., drop = drop) : 
  samples specified, expecting a numeric, character or logical but received integer
```

**Comment by knausb** [comment]
Added integer handling at: 64a308ba50b9119108e8946737460de5997b805b

**Comment by zkamvar** [comment]
👍
