### ISSUE TITLE
Registration of symbols

### ISSUE THREAD

**Issue by knausb** [knausb/vcfR#63]
As posted elsewhere:

https://github.com/RcppCore/Rcpp/issues/636

vcfR now generates a NOTE on R-devel. This was confirmed on winbuilder.

**Comment by zkamvar** [comment]
I had a similar note in poppr. If you're interested, I had also read through the above thread and found a solution that worked for me and may also work for you: 
https://github.com/grunwaldlab/poppr/issues/124#issuecomment-284248907

**Comment by knausb** [comment]
This seems to have fixed this:

https://github.com/RcppCore/Rcpp/issues/636#issuecomment-280985661

This may be of future reference:
https://ironholds.org/registering-routines/

**Comment by knausb** [comment]
Went with the directions here:

https://ironholds.org/registering-routines/

and it tests correct on win-builder.
