### ISSUE TITLE
clang: error: unsupported option '-fopenmp'

### ISSUE THREAD

**Issue by knausb** [knausb/vcfR#64]
Upgraded to R 3.4.0, "You Stupid Darkness". When building on Mac I now receive:

clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o vcfR.so NM2winNM.o RcppExports.o ad_frequency.o extractGT2NM.o freq_peak.o gt_to_popsum.o is_het.o masplit.o pair_sort.o rank_variants.o seq_to_rects.o var_window.o vcfRCommon.o vcf_io.o -fopenmp -lgomp -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
clang: error: unsupported option '-fopenmp'
make: *** [vcfR.so] Error 1
ERROR: compilation failed for package ‘vcfR’

**Comment by knausb** [comment]
Note that it appears to be building at CRAN with 3.40, so this is likely specific to my system.

**Comment by zkamvar** [comment]
Hi Brian, I ran into a similar issue. If it helps, I'm posting the way I was able to fix it on my machine. If it doesn't help, then feel free to ignore/delete this.

Documented here: https://cloud.r-project.org/bin/macosx/tools/

CRAN has updated to clang 4.0, which is not distributed for OSX. I downloaded clang from r.research.att.com/libs.

The instructions are to un-tar it to `/`, where it would install at `/usr/local/clang4`. Because of the permissions issues in Sierra, I always got an error that it couldn't modify `/usr/` even though Apple says it's okay to install things into `/usr/local`, so I un-tar'd it where it was, and moved the output from `./usr/local/clang4` to `/usr/local/clang4`.


As suggested by CRAN, I then modified my ~/.R/Makevars file to the following (as specified by CRAN):

```
# Using clang 4, which has openMP support
CC = /usr/local/clang4/bin/clang
CXX = /usr/local/clang4/bin/clang++
CFLAGS = -g -O2 -Wall -pedantic -Wconversion -Wno-sign-conversion
CXXFLAGS = -g -O2 -Wall -pedantic -Wconversion -Wno-sign-conversion
#CXX11 = $CXX
CXX11 = /usr/local/clang4/bin/clang++
```

**Comment by knausb** [comment]
The clang version sounds spot on! But now I'm generating a segmentation fault. I suspect it has something to do with the contents of my ~/Makevars. Perhaps some quality time on writing R extensions will help me sort that out.

Thanks Zhian!

**Comment by zkamvar** [comment]
I reinstalled all of my packages and now I only have segmentation faults when I use devtools, but I can't seem to figure out what's triggering it. It is quite frustrating 😣 

Do your segfaults look something like this by any chance

```
 *** caught segfault ***
address 0x0, cause 'memory not mapped'

Traceback:
 1: getDLLRegisteredRoutines.DLLInfo(dll, addNames = FALSE)
 2: assignNativeRoutines(dlls[[lib]], lib, env, nsInfo$nativeRoutines[[lib]])
 3: load_dll(pkg)
 4: devtools::load_all()
```

**Comment by knausb** [comment]
I'm getting:

```
** R
** data
** inst
** preparing package for lazy loading

 *** caught segfault ***
address 0x0, cause 'memory not mapped'

Traceback:
 1: getDLLRegisteredRoutines.DLLInfo(dll, addNames = FALSE)
 2: assignNativeRoutines(dlls[[lib]], lib, env, nsInfo$nativeRoutines[[lib]])
 3: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
 4: namespaceImport(ns, loadNamespace(i, c(lib.loc, .libPaths()),     versionCheck = vI[[i]]), from = package)
```

But I'm afraid its a bit mysterious to me. I want to believe it is compiling.

**Comment by knausb** [comment]
Well, I went scorched earth and removed most of my packages and re-installed them. From R:

```
# Base packages, and should not be updated
myBase <- c('base', 'compiler', 'datasets', 'graphics', 'grDevices', 'grid', 'methods', 'parallel', 'splines', 'stats', 'stats4', 'tcltk', 'tools', 'utils')

miss.pkgs <- list.files("/Users/knausb/R/")
miss.pkgs <- grep(paste(myBase, collapse = "|"), miss.pkgs, value = TRUE, invert = TRUE)
remove.packages(miss.pkgs, lib = "/Users/knausb/R/")
```

And reinstall. Now vcfR magically builds and passes all tests. Zero points for elegance, but it worked. And for the record, my ~.R/Makevars file now looks like:

```
CC = /usr/local/clang4/bin/clang
CXX = /usr/local/clang4/bin/clang++
CXX11 = /usr/local/clang4/bin/clang++
# Linker flags
PKG_LIBS = -fopenmp -lgomp
# Link directives
LDFLAGS=-L/usr/local/clang4/lib
# Compiler flags
CFLAGS = -g -O2 -Wall -pedantic -Wconversion -Wno-sign-conversion
CXXFLAGS = -g -O2 -Wall -pedantic -Wconversion -Wno-sign-conversion
```

And as a reminder, this is Mac (OSX) specific.

**Comment by zkamvar** [comment]
Just adding a note here in case others find it useful. 

The segfaults I was running into with building my package locally was due to `*.so` files hanging around in my `src/` directory built with the previous version of R with a different C compiler. Removing these files fixed the problem.

**Comment by knausb** [comment]
Some of us us a file called 'cleanup' to help with this task.

https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Configure-and-cleanup

Thanks Zhian!

**Comment by BeatriceGR** [comment]
@zkamvar Hi! I did as you said and tried to move the output from ./usr/local/clang4 to /usr/local/clang4 and it says Permission denied. Do you have any idea why?

**Comment by zkamvar** [comment]
Hi @BeatriceGR, my first guess would be that you have to use `sudo`. I believe that's what I did since all of the files in clang4 are from root:

```
$ ls -larth /usr/local/clang4/
total 0
drwxr-xr-x    8 root   wheel   272B Apr  4 16:47 include
drwxr-xr-x    6 root   wheel   204B Apr  4 16:47 share
drwxr-xr-x@   7 root   wheel   238B Apr  4 16:47 clang4
drwxr-xr-x    4 root   wheel   136B Apr 23 16:28 libexec
drwxr-xr-x  182 root   wheel   6.0K Apr 23 16:28 lib
drwxr-xr-x   62 root   wheel   2.1K Apr 23 16:28 bin
drwxr-xr-x    8 root   wheel   272B Apr 23 16:46 .
drwxr-xr-x   22 zhian  wheel   748B Jun  9 09:51 ..
```

Hope that helps!

**Comment by BeatriceGR** [comment]
@zkamvar thanks! I'll try it!

**Comment by teuschb** [comment]
Could somebody help me figure out where to find my makevars file? All the advice refers to it but I can't find it anywhere.

**Comment by zkamvar** [comment]
Hi @teuschb, 

If you are on OSX or any other UNIX system (read: not Windows), you Makevars file will be in `~/.R/Makevars`. If you are unfamiliar with command line syntax, `~` is a shortcut for your home folder. You can find out where this is on your computer by typing `echo $HOME` in your terminal.

You may also want to wade through a comprehensive explanation of the Makevars file in this stackoverflow post: https://stackoverflow.com/a/43599233/2752888
