### ISSUE TITLE
read_vcf3.cpp error using zlib

### ISSUE THREAD

**Issue by Tabima** [knausb/vcfR#7]
For new ubuntu users using 14.04 LTS, there is a new version of zlib (zlib 1.2.8). this version breaks read_vcf3.cpp on line 772.

to fix the error, I changed the pointer in line 732:

```
-   gzFile *fi = (gzFile *)gzopen(filename.c_str(),"ab");
+   gzFile fi = (gzFile )gzopen(filename.c_str(),"ab");
```

**Comment by knausb** [comment]
I've actually been working on this exact line to achieve a successful windows build.  The line you changed appears to be from the master branch.  Could you try this with the devel branch and report your results?

**Comment by Tabima** [comment]
Tried the devel branch and worked:
```
devtools::install_github("knausb/vcfR", ref="devel")
```

**Comment by knausb** [comment]
Thanks, I'll work on merging devel to master soon.
