### ISSUE TITLE
vcf_stats_gz should not scan entire file when entire file is not desired

### ISSUE THREAD

**Issue by knausb** [knausb/vcfR#70]
@rcorty identified a way to improve the performance of `read.vcfR()` When the entire file is not intended to be read in to R. This was in pull request #69. We discussed the matter and agreed that there may be a better manner to implement his suggestion. At the time, neither of us had time to address this. This issue was raised to remind me to address this matter.

**Comment by knausb** [comment]
Hi @rcorty, still out there? This one took me a bit to get back to. But I think I've implemented your suggestion. If you'd like to give it a try, and you have a compiler, you can use the following to install the GitHub version.

```
devtools::install_github(repo="knausb/vcfR")
```

Let me know if it's what you were hoping for.

**Comment by rcorty** [comment]
Hi @knausb -- looks great -- thanks!

**Comment by knausb** [comment]
Thank you!
