### ISSUE TITLE
how to load my.vcf.gz file into vcfR?

### ISSUE THREAD

**Issue by psddia** [knausb/vcfR#83]
I've read through the tutorial, and you load your VCF file from a package you created. Could you walk me through how you would load a VCF file downloaded from 1000 genomes. I'm using the ChrY file to learn on, since it's small. I'm new to R and VCF files. I was able to load everything and recreate the graphs in the tutorial, but I can't even get the chrY VCF to get into R properly and renamed the generic "vcf_file".

Your help is much appreciated.

**Comment by knausb** [comment]
Hello,

Have you seen the example here: [https://knausb.github.io/vcfR_documentation/vcf_data.html](https://knausb.github.io/vcfR_documentation/vcf_data.html)?

Human has a large genome relative to the ones I typically work with. This means you may exceed your system resources by trying to read it in. If you subset your files it may improve access time and save RAM. I've an example here:

[https://knausb.github.io/vcfR_documentation/subset_data_to_1chrom.html](https://knausb.github.io/vcfR_documentation/subset_data_to_1chrom.html)

Its sounds like you have already done that, but you may be able to re-purpose the example if file size is an issue. Also, `read.vcfR()` can read in portions of a file with options `nrows`, `skip`, and `cols`. You can find its documentation as follows.

```
?vcfR::read.vcfR
```

Does that get you the information you need?
Brian

**Comment by psddia** [comment]
My problem is more elementary. I have the Y chromosome from 1000 genes on my hard drive. How do I load it to R, so that I can then use the read.vcfR script?
I'm sorry for the super basic question, but I don't even know how to tell vcfR where to look for my VCF file on my hard drive.
Does that make sense?

**Comment by knausb** [comment]
This depends a bit on what platform you are using: Windows, Mac, or Linux. When you start R it will have a 'working directory'. You can query this as follows.

```
getwd()
```

If your VCF file is in your working directory you should be able to use something like

```
vcf <- read.vcfR('myData.vcf.gz')
```

If your file is not in your working directory you can either move to it.

```
setwd('directory_where_your_data_is')
```

or include the path in the call.

```
vcf <- read.vcfR('directory_where_your_data_is/myData.vcf.gz')
```

The specifics will differ depending on what OS you're using. So if this doesn't give you your answer and you ask for more help I really need to know whether you're using Windows, Mac, or Linux. Also if you're using RStudio would help.

Good luck!
Brian

**Comment by psddia** [comment]
Perfect, thanks for your help! Got it loaded and am fooling around to get the hang of it.

**Comment by knausb** [comment]
Yay! Good luck!
Brian
