### ISSUE TITLE
Neucleotide frequency analysis

### ISSUE THREAD

**Issue by psddia** [knausb/vcfR#84]
Is there a way to get an ATCG nucleotide frequency for each subject contained in the VCF file? I want to calculate the percent of A, T, C, G for the entire subject, then compare that against all other subjects in the VCF file. Any suggestions?

**Comment by knausb** [comment]
VCF data only contains information about the **variable** positions, not the entire chromosome. But you could use this information to make relative comparisons. Have you looked at the documentation for `extract.gt()` or `extract.haps()`?

**Comment by knausb** [comment]
Closed due to lack of reply.
