### ISSUE TITLE
read.vcfR doesn't work with network locations

### ISSUE THREAD

**Issue by V-Z** [knausb/vcfR#88]
Hello,
when I try
```
arabidopsis.vcf <- read.vcfR(file="https://soubory.trapa.cz/rcourse/arabidopsis.vcf")
Error in read.vcfR(file = "https://soubory.trapa.cz/rcourse/arabidopsis.vcf") : 
  File: https://soubory.trapa.cz/rcourse/arabidopsis.vcf does not appear to exist!
```
But

1. the file exists and is readable (e.g. in BASH `wget https://soubory.trapa.cz/rcourse/arabidopsis.vcf`) and
2. `arabidopsis.vcf <- read.vcfR(file=file.choose())` or so processes the downloaded file correctly.

Similar functions from e.g. `ape` reading FASTA, NEXUS, NEWICK, ... work well with network addresses... so I consider this as a bug.

**Comment by knausb** [comment]
Thanks for reporting this! However, I'm not convinced this is a good idea. Perhaps you can convince me?

I don't agree that this is a 'bug'. No where in the documentation do I claim this sort of functionality. So its not that the code does not do what its supposed to. Its that you want new functionality. Let's call this a 'feature request.' Some of us get a little sensitive when someone claims our code is buggy.

Thank you for providing an example. This helps illustrate the functionality you desire. But I question whether this is a good idea. Reading files through a network will typically present a large bottleneck in your workflow. For example, when I time your example I see the following.

```
system.time(system('wget https://soubory.trapa.cz/rcourse/arabidopsis.vcf'))
```

```
##    user  system elapsed 
##   0.020   0.008   3.348
```

And when I read a file from disk I see this.

```
library(vcfR)
system.time(vcf <- read.vcfR('arabidopsis.vcf'))
```

```
##    user  system elapsed 
##   0.100   0.004   0.104
```

Downloading the file requires noticeable time, while reading it into R does not. At 291 samples and 309 variants I would consider this to be a modestly sized file. I'm used to working with data that is typically 10s, 100s of thousand or millions of variants. Some of these files take a noticeable amount of time to read in. I would expect them to take a considerable amount of time to download. If during the analysis of this data the original data was clobbered and then the analyst decided they needed the original data back they would have to re-download the file. I don't see this as an efficient way of going about this. I would consider it a good practice to always have a local copy of your data. Do you see my point? Do you see something I do not?

Thanks!

**Comment by V-Z** [comment]
Hello,
thank You for Your reply. If You dislike calling it a bug, we can call it a feature request, the "bug" is not meant offensively. There are two basic reasons why I considered this as a bug:

 1. In other commonly used import functions this work, so I thought handling of any file location (including web address) is basic default behavior (with some internal R function or so) and its lack is then a bug.
 2. The error message says it can't find requested file (while it exists). If it'd say something like "Web URLs are not supported", then I wouldn't call it a bug, of course.

In this very particular use case, for teaching, it is easier to provide students with a script file to work with and download files from the Internet directly into R. Of course, web download will always be slower, but You do it only once - You can export the VCF and reuse it if needed. Generally, I do consider direct web access very convenient especially for sharing, using web resources, and so.

So this is my basic rationale for this feature. If I didn't convince You, consider, please, update of the error message. In any case, thank You for this nice package.

**Comment by zkamvar** [comment]
Hello @V-Z,

In the case it helps: a temporary solution would be to first download the file into a temporary directory using `download.file()`. This way, it will work regardless of the ultimate decision. 

``` r
library("vcfR")
#> 
#>    *****       ***   vcfR   ***       *****
#>    This is vcfR 1.6.0 
#>      browseVignettes('vcfR') # Documentation
#>      citation('vcfR') # Citation
#>    *****       *****      *****       *****
(tmp <- tempfile(fileext = "-arabadopsis.vcf.gz")) # Create a temporary file for holding the downloaded data
#> [1] "/var/folders/qd/dpdhfsz12wb3c7wz0xdm6dbm0000gn/T//RtmpHc4bo4/file8069b9f693-arabadopsis.vcf.gz"
download.file(url = "https://soubory.trapa.cz/rcourse/arabidopsis.vcf", destfile = tmp)
(arabadopsis.vcf <- read.vcfR(file = tmp))
#> Scanning file to determine attributes.
#> File attributes:
#>   meta lines: 763
#>   header line: 764
#>   variant count: 309
#>   column count: 300
#> 
Meta line 763 read in.
#> All meta lines processed.
#> gt matrix initialized.
#> Character matrix gt created.
#>   Character matrix gt rows: 309
#>   Character matrix gt cols: 300
#>   skip: 0
#>   nrows: 309
#>   row_num: 0
#> 
Processed variant: 309
#> All variants processed
#> ***** Object of Class vcfR *****
#> 291 samples
#> 1 CHROMs
#> 309 variants
#> Object size: 2.6 Mb
#> 0 percent missing data
#> *****        *****         *****
unlink(tmp)                                        # Remove the file that we downloaded
```

Created on 2018-01-18 by the [reprex
package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by V-Z** [comment]
This is a nice trick, thank You, @zkamvar, it is on half way between current state and my ideal state. :-)

**Comment by knausb** [comment]
Hi @V-Z, functions such as `utils::read.table()` can handle either a file or a connection. So if my function was some sort of wrapper to this one it would be trivial. However, `utils::read.table()` it was never intended to read files the size of most VCF files. Our desire to have a fast way to get VCF data into R was one of the inspirations for creating vcfR. In order to gain that performance we used the Rcpp interface to C++ so that `vcfR::read.vcfR()` is mostly written in C++. So depending on how we approach this it could be a C++ issue instead of R. If its a C++ issue I think this might not be as simple as you may have thought and that was a large part of my hesitation.

I like @zkamvar 's idea. But I don't think it gets us all the way there. How about this.

First, we need to determine if we have a file or a url. If the user provides a file that begins with http://, https://, ftp://, or ftps:// we'll call it a url (this follows `readr::read_delim()`).

If it is a url we download it using `utils::download.file()`. But let's put it in the current working directory. We can then throw a message that says we've downloaded the file and the user should use the local file in the future instead. Actually, we can test if the file name to be downloaded exists in the working directory and if its there use it instead of the download. We can include a message informing the user we're using a local file instead.

Once we have the file, we read it in with existing code.

And I think we should leave it to the user to delete the file if they feel that's necessary. That would allow them to re-import the file if they choose to.

Would that be a good balance between @V-Z 's desire to automatically download a file and my desire to avoid repeated downloads? (And it keeps the solution in R.)

**Comment by V-Z** [comment]
Thank You, @knausb for the explanation. I see, implementation of such functionality would be too complicated. Your idea seems perfect to me. It does exactly what user would suppose.

**Comment by knausb** [comment]
Hi @V-Z , I've added the changes to 7d8e3d28dbe894bdbcf066f327aeea8cad09add2 and they're now on the master branch. You can give it a try if you'd like. However, you'll need a compiler to build the GitHub version. Our current plan is to have a CRAN release in February when you should find your changes in v1.7.0.

Thanks!

**Comment by V-Z** [comment]
Thank You, @knausb for the fix. But I have an issue with it:
```
arabidopsis.vcf <- read.vcfR(file="https://soubory.trapa.cz/rcourse/arabidopsis.vcf")
[1] "Yup"
Downloading remote file https://soubory.trapa.cz/rcourse/arabidopsis.vcf
trying URL 'https://soubory.trapa.cz/rcourse/arabidopsis.vcf'
Content type 'text/vcard' length 3498419 bytes (3.3 MB)
==================================================
downloaded 3.3 MB

File downloaded.
It will probably be faster to use this local file in the future instead of re-downloading it.
Error in read.vcfR(file = "https://soubory.trapa.cz/rcourse/arabidopsis.vcf") :
  File: https://soubory.trapa.cz/rcourse/arabidopsis.vcf does not appear to exist!
```
It seems the file is correctly downloaded (it is in the working directory), but `read.vcf()` does not receive updated `file` location.

**Comment by zkamvar** [comment]
Hi @V-Z, 

It should be fixed as of 1d84c52. Try re-installing vcfR.

**Comment by knausb** [comment]
Hi @V-Z, you are correct. Apologies. @zkamvar has helped us out, thanks! I now have the following.

``` r


# File is remote

library(vcfR)
#> 
#>    *****       ***   vcfR   ***       *****
#>    This is vcfR 1.6.0.9000 
#>      browseVignettes('vcfR') # Documentation
#>      citation('vcfR') # Citation
#>    *****       *****      *****       *****
unlink('arabidopsis.vcf')
vcf <- read.vcfR('https://soubory.trapa.cz/rcourse/arabidopsis.vcf')
#> Downloading remote file https://soubory.trapa.cz/rcourse/arabidopsis.vcf
#> File downloaded.
#> It will probably be faster to use this local file in the future instead of re-downloading it.
#> Scanning file to determine attributes.
#> File attributes:
#>   meta lines: 763
#>   header line: 764
#>   variant count: 309
#>   column count: 300
#> 
Meta line 763 read in.
#> All meta lines processed.
#> gt matrix initialized.
#> Character matrix gt created.
#>   Character matrix gt rows: 309
#>   Character matrix gt cols: 300
#>   skip: 0
#>   nrows: 309
#>   row_num: 0
#> 
Processed variant: 309
#> All variants processed
vcf
#> ***** Object of Class vcfR *****
#> 291 samples
#> 1 CHROMs
#> 309 variants
#> Object size: 2.6 Mb
#> 0 percent missing data
#> *****        *****         *****
rm(vcf)

# File is local but url is provided

vcf <- read.vcfR('https://soubory.trapa.cz/rcourse/arabidopsis.vcf')
#> Local file arabidopsis.vcf found.
#> Using this local copy instead of retrieving a remote copy.
#> Scanning file to determine attributes.
#> File attributes:
#>   meta lines: 763
#>   header line: 764
#>   variant count: 309
#>   column count: 300
#> 
Meta line 763 read in.
#> All meta lines processed.
#> gt matrix initialized.
#> Character matrix gt created.
#>   Character matrix gt rows: 309
#>   Character matrix gt cols: 300
#>   skip: 0
#>   nrows: 309
#>   row_num: 0
#> 
Processed variant: 309
#> All variants processed
vcf
#> ***** Object of Class vcfR *****
#> 291 samples
#> 1 CHROMs
#> 309 variants
#> Object size: 2.6 Mb
#> 0 percent missing data
#> *****        *****         *****
rm(vcf)

# File is local

vcf <- read.vcfR('arabidopsis.vcf')
#> Scanning file to determine attributes.
#> File attributes:
#>   meta lines: 763
#>   header line: 764
#>   variant count: 309
#>   column count: 300
#> 
Meta line 763 read in.
#> All meta lines processed.
#> gt matrix initialized.
#> Character matrix gt created.
#>   Character matrix gt rows: 309
#>   Character matrix gt cols: 300
#>   skip: 0
#>   nrows: 309
#>   row_num: 0
#> 
Processed variant: 309
#> All variants processed
vcf
#> ***** Object of Class vcfR *****
#> 291 samples
#> 1 CHROMs
#> 309 variants
#> Object size: 2.6 Mb
#> 0 percent missing data
#> *****        *****         *****
```

Created on 2018-01-19 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by V-Z** [comment]
This works perfectly! Thank You, @knausb and @zkamvar!
