### ISSUE TITLE
cbind in vcfr2tidy insensitive to duplicate column names

### ISSUE THREAD

**Issue by ripkrizbi** [knausb/vcfR#91]
Silly example: SnpSift annotates vcf files with an info field named REF:

`##INFO=<ID=REF,Number=0,Type=Flag,Description="Has reference A coding region variation where one allele in the set is identical to the reference sequence. FxnCode = 8">`

which in turn breaks vcfr2tidy with the error `Column 'REF' must have a unique name` in `dplyr::left_join`.

The base and fixed part of the info are bound by `cbind`, which seems to tolerate duplicate colnames, but the left_join that follows does not and the whole thing breaks. 
Not sure if the info field with the name "REF" is allowed by the VCF spec, but a quick fix for this would be to use `dplyr::bind_cols`, which corrects duplicate names on the fly (second REF is renamed to REF1).

https://github.com/knausb/vcfR/blob/a23485f1b34b47756c2474951d775c6475b640d1/R/vcfR_to_tidy_functions.R#L265-L266

https://github.com/knausb/vcfR/blob/a23485f1b34b47756c2474951d775c6475b640d1/R/vcfR_to_tidy_functions.R#L286-L287

https://github.com/knausb/vcfR/blob/a23485f1b34b47756c2474951d775c6475b640d1/R/vcfR_to_tidy_functions.R#L303-L304

**Comment by knausb** [comment]
Hi @ripkrizbi, I've never used SnpSift, so thank you for pointing this out. However, I do not follow the issue.

Section 1.4.2 of the VCF specification v4.3 describes the INFO field format. It specifies what keys are allowed but the example you've provided uses `REF` as a value of the pair. So this appears to be in line with the specification.

However, I do not appear to be able to reproduce your error. Here's my attempt at a reproducible example.

```
data("vcfR_test")
myMeta <- vcfR_test@meta
vcfR_test@meta <- c(myMeta[1:12], '##INFO=<ID=REF,Number=0,Type=Flag,Description="Has reference A coding region variation where one allele in the set is identical to the reference sequence. FxnCode = 8">', myMeta[13:18])  
Z <- vcfR2tidy(vcf, info_only = FALSE, verbose = FALSE)
Z$meta
# A tibble: 23 x 7
     Tag              ID Number    Type
   <chr>           <chr>  <chr>   <chr>
 1  INFO              AC      A Integer
 2  INFO              AF      A   Float
 3  INFO              AN      1 Integer
 4  INFO    BaseQRankSum      1   Float
 5  INFO ClippingRankSum      1   Float
 6  INFO              DP      1 Integer
 7  INFO              DS      0    Flag
 8  INFO              FS      1   Float
 9  INFO  HaplotypeScore      1   Float
10  INFO InbreedingCoeff      1   Float
# ... with 13 more rows, and 3 more variables: Description <chr>, Source <chr>, Version <chr>
```

I do not generate an error. Is the issue that you have multiple records that include `ID=REF`?

**Comment by ripkrizbi** [comment]
Hi Brian, I think the  reason why you do not get the error might be because you're converting the `vcf` object, rather than the `vcfR_test` one.

If I try to use the correct var, this is what I get:

```r
> data("vcfR_test")
> myMeta <- vcfR_test@meta
> vcfR_test@meta <- c(myMeta[1:12], '##INFO=<ID=REF,Number=0,Type=Flag,Description="Has reference A coding region variation where one allele in the set is identical to the reference sequence. FxnCode = 8">', myMeta[13:18])  
> Z <- vcfR2tidy(vcfR_test, info_only = FALSE, verbose = FALSE)
Error: Column `REF` must have a unique name
```
 
Hope it helps...

**Comment by knausb** [comment]
Oops! You're correct on that. Never hurts to refresh your environment 😄. Thanks for your suggestion. I've implemented it. And in doing so I've realized that `dplyr::tbl_df()` has been deprecated and the recommended replacement is `tibble::tibble()`. So whether you know it or not you helped me with that one too. This has been pushed to master now. If you'd like to try it and provide any feedback please do.

**Comment by ripkrizbi** [comment]
Hi @knausb sorry for being late on this too - works as advertised, I'm very happy with the fix! Many thanks for your prompt response(s)!

**Comment by knausb** [comment]
Thank you!
