### ISSUE TITLE
VCFR2migrate

### ISSUE THREAD

**Issue by shankarkshakya** [knausb/vcfR#93]
I realized that vcfr2migrate output file that I produced didnt run even though the format looked alright. Running dos2unix on output migrate-n file solved the problem. Enjoy.

**Comment by knausb** [comment]
We  could also create a parameter `eol = "\n"` like the one used by `write.table()`. I'd prefer that because I think it would get the user where they're going faster because they may not know about `dos2unix`. In fact, some systems use `fromdos` instead, which could be confusing.

**Comment by knausb** [comment]
Added at 8291a6d443e1df57aa1e7f0bb4f19395b21ac1ff. Thanks Shankar!
