### ISSUE TITLE
empty VCF: 'data' must be of a vector type, was 'NULL'

### ISSUE THREAD

**Issue by igordot** [knausb/vcfR#97]
I can import an empty VCF (with header, but without variants):
```
> muts_vcfr = read.vcfR(mutect_vcf)
Scanning file to determine attributes.
File attributes:
  meta lines: 249
  header line: 250
  variant count: 0
  column count: 11
Meta line 249 read in.
All meta lines processed.
gt matrix initialized.
Character matrix gt created.
  Character matrix gt rows: 0
  Character matrix gt cols: 11
  skip: 0
  nrows: 0
  row_num: 0
Processed variant: 0
All variants processed
```
However, if I try to convert that object to a data frame, I get an error:
```
> muts_tbl = vcfR2tidy(muts_vcfr)
Error in matrix(., ncol = length(info_fields), byrow = TRUE) : 
  'data' must be of a vector type, was 'NULL'
```
It makes sense that it fails. However, it might be nice to add a check so the error is more informative.

**Comment by knausb** [comment]
If I've allowed a vcfR object to contain no variants then I sort of think vcfR should handle this. Although I can't think of why someone would. Although people like you raise issues when they come up with things I never thought of  :laughing:. Technically the issue was that `extract_info_tidy()` and `extract_gt_tidy()`, which are called by `vcfR2tidy()`, threw errors. And while we're being technical, `vcfR2tidy()` creates a `tibble` which is a special type of `data.frame`. We should now be able to handle situations where there are no variants: 3ced1e7d000ab6286104f8f10687a438b6f857f1. New behaviour is as follows.

```
> data("vcfR_test")
> vcf <- vcfR_test[0,]
> extract_info_tidy(vcf)
# A tibble: 0 x 7
# ... with 7 variables: Key <int>, NS <int>, DP <int>, AF <lgl>, AA <lgl>, DB <lgl>, H2 <lgl>
> extract_gt_tidy(vcf)
Extracting gt element GT
Extracting gt element GQ
Extracting gt element DP
Extracting gt element HQ
# A tibble: 0 x 7
# ... with 7 variables: Key <int>, Indiv <int>, gt_GT <chr>, gt_GQ <int>, gt_DP <int>, gt_HQ <chr>,
#   gt_GT_alleles <chr>
> vcfR2tidy(vcf)
Extracting gt element GT
Extracting gt element GQ
Extracting gt element DP
Extracting gt element HQ
$fix
# A tibble: 0 x 14
# ... with 14 variables: ChromKey <int>, CHROM <chr>, POS <int>, ID <chr>, REF <chr>, ALT <chr>, QUAL <dbl>,
#   FILTER <chr>, NS <int>, DP <int>, AF <lgl>, AA <lgl>, DB <lgl>, H2 <lgl>

$gt
# A tibble: 0 x 8
# ... with 8 variables: ChromKey <int>, POS <int>, Indiv <int>, gt_GT <chr>, gt_GQ <int>, gt_DP <int>,
#   gt_HQ <chr>, gt_GT_alleles <chr>

$meta
# A tibble: 10 x 5
   Tag    ID    Number Type    Description                
   <chr>  <chr> <chr>  <chr>   <chr>                      
 1 INFO   NS    1      Integer Number of Samples With Data
 2 INFO   DP    1      Integer Total Depth                
 3 INFO   AF    A      Float   Allele Frequency           
 4 INFO   AA    1      String  Ancestral Allele           
 5 INFO   DB    0      Flag    dbSNP membership, build 129
 6 INFO   H2    0      Flag    HapMap2 membership         
 7 FORMAT gt_GT 1      String  Genotype                   
 8 FORMAT gt_GQ 1      Integer Genotype Quality           
 9 FORMAT gt_DP 1      Integer Read Depth                 
10 FORMAT gt_HQ 2      Integer Haplotype Quality          
```

Currently on the master branch and can be installed as follows.

```
devtools::install_github(repo="knausb/vcfR")
```

Note that this will require a compiler.
Thanks!
Brian

**Comment by igordot** [comment]
Thank you for the quick fix!

If you are working with a small region, you may end up with no variants. You probably don't need a tool like vcfR to process an empty a VCF, but you may not realize it's empty, especially if you are processing many samples at a time. You don't want to the whole process to crash, though.

**Comment by knausb** [comment]
Ahh! You've reminded me. Small contigs may not have variants. And if you're processing a directory of VCF files we want to be able to process them all. So it makes sense. I just don't tend to use the tidy functions much. Thanks!
